### ISSUE TITLE
Pipeline is displayed on both Dev and Live containers

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/nationalparks#7]
Pipeline is annotated with both Dev and Live deploymentconfigs and therefore it is displayed twice in the console:
```
pipeline.alpha.openshift.io/uses: '[{"name": "nationalparks-dev", "namespace": "", "kind": "DeploymentConfig"},{"name": "nationalparks-live", "namespace": "", "kind": "DeploymentConfig"}]'
```
![pipeline](https://cloud.githubusercontent.com/assets/1174934/20795313/d52748fe-b7d0-11e6-9927-7f5410d1099d.png)

Pipeline visualization in its current form attached to either of them does not make much sense. We should probably remove the annotations and just show the pipeline in *Builds* &rarr; *Pipelines*

**Comment by thoraxe** [comment]
This is by design according to engineering.

The live deployment is associated with the dev deployment via the pipeline. Why would you not want to know that the live deployment has an incoming deployment associated with the pipeline?

I think it makes perfect sense. You would need to discuss with spadgett and/or jwforres to get more background. Possibly gmontero and/or bparees.

**Comment by siamaksade** [comment]
It looks like there are 2 pipelines being executed while that is not true. Only one pipeline is running.

**Comment by thoraxe** [comment]
While it looks like that, they both have the same name, the same status, and display the exact same information.

If you want to pull it, go for it. But we also need to file bugs with engineering so that the behavior works better if you think it's not clear.

**Comment by siamaksade** [comment]
I created an issue https://github.com/openshift/origin-web-console/issues/972

Let's add either dev or live to the annotation for now to make it display once. Otherwise, we'll have to explain this to people
